/* Generated By:JavaCC: Do not edit this line. SyntaxCheckerConstants.java */
package edu.buffalo.cse.sql;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SyntaxCheckerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CTCMD = 5;
  /** RegularExpression Id. */
  int SELECT = 6;
  /** RegularExpression Id. */
  int JOIN = 7;
  /** RegularExpression Id. */
  int ON = 8;
  /** RegularExpression Id. */
  int WHERE = 9;
  /** RegularExpression Id. */
  int AS = 10;
  /** RegularExpression Id. */
  int NOT_TRUE = 11;
  /** RegularExpression Id. */
  int BOOLEAN_AND_CONDITION = 12;
  /** RegularExpression Id. */
  int BOOLEAN_OR_CONDITION = 13;
  /** RegularExpression Id. */
  int UNION = 14;
  /** RegularExpression Id. */
  int FROM = 15;
  /** RegularExpression Id. */
  int AND = 16;
  /** RegularExpression Id. */
  int OR = 17;
  /** RegularExpression Id. */
  int TOK = 18;
  /** RegularExpression Id. */
  int OBRA = 19;
  /** RegularExpression Id. */
  int CBRA = 20;
  /** RegularExpression Id. */
  int TNAME = 21;
  /** RegularExpression Id. */
  int NUMBER = 22;
  /** RegularExpression Id. */
  int EXPONENT = 23;
  /** RegularExpression Id. */
  int COMMA = 24;
  /** RegularExpression Id. */
  int APOS = 25;
  /** RegularExpression Id. */
  int SEMICOLON = 26;
  /** RegularExpression Id. */
  int DOT = 27;
  /** RegularExpression Id. */
  int OPCODE = 28;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"Create Table\"",
    "\"SELECT\"",
    "\"JOIN\"",
    "\"ON\"",
    "\"WHERE\"",
    "\"AS\"",
    "\"not true\"",
    "\"true and false\"",
    "\"true or false\"",
    "\"UNION\"",
    "\"FROM\"",
    "\"AND\"",
    "\"OR\"",
    "<TOK>",
    "\"(\"",
    "\")\"",
    "<TNAME>",
    "<NUMBER>",
    "<EXPONENT>",
    "\",\"",
    "\"\\\'\"",
    "\";\"",
    "\".\"",
    "<OPCODE>",
  };

}
